name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */4 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Set Lichess Key
        run: echo "LICHESS_KEY=${{ secrets.LICHESS_KEY }}" >> $GITHUB_ENV

      - name: Run bot
        run: |
          chmod +x ./engines/stockfish
          python3 user_interface.py --config config.yml
